routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'TicketController@index');

Route::post('ticket/search', 'TicketController@search');
Route::post('ticket/filter', 'TicketController@filter');
Route::resource('ticket','TicketController');

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    //
    protected $fillable = [
        'nombre', 'descripcion', 'importancia',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Ticket;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ticket = Ticket::all();
        return view('home')->with(['tickets'=> $ticket]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("home")->with('create',true);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nombre' => 'required',
            'descripcion' => 'required',
            'importancia' => 'required',
        ]); 

        $ticket = new Ticket();
        $ticket->nombre = $request->nombre;
        $ticket->descripcion = $request->descripcion;
        $ticket->importancia = $request->importancia;

        if ($ticket->save()) {
            return redirect('/');
        } else {
            return back()->with('errormsj', 'Los datos no se guardaron');  
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ticket = Ticket::find($id);
        return view('home')->with(['edit'=>true, 'ticket'=>$ticket]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        $this->validate($request, [
            'nombre' => 'string',
            'descripcion' => 'string',
        ]);

        $ticket = Ticket::find($id);
        $ticket->descripcion = $request->descripcion;
        $ticket->importancia = $request->importancia;

        if ($ticket->save()) {
            return redirect('/');
        } else {
            return back()->with('errormsj', 'Los datos no se actualizaron');  
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Ticket::destroy($id);
        return redirect('/');
    }

    public function search(Request $request)
    {

        $ticket = Ticket::where('nombre','like','%'.$request->search.'%')->orWhere('descripcion','like','%'.$request->search.'%')->get();

       return view('home', ['buscado'=>true,'tickets' => $ticket]);
    }

    public function filter(Request $request)
    {   
        $ticket = Ticket::where('importancia',(int)$request->importancia)->get();

        return view('home', ['filtrado'=>true, 'tickets' => $ticket]);
    }
}

resources/views/home.blade.php
@extends('layouts.app')
	@section('title')
		@parent
	@endsection
	@section('content')

		@if(isset($edit))
			@include('layouts/form_ticket')
		@elseif(isset($create))
			@include('layouts/form_ticket')
		@else
			@include('layouts/table_ticket')
		@endif
	@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap.min.css')}}">
	<script type="text/javascript" src="{{ asset('js/bootstrap.min.js') }}"></script>
	<title>Gestion de Ticket.</title>
</head>
<body class="col-xs-9">
@section('title')
	<h1>Gestion de Ticket.</h1>
@show
@yield('content')
</body>
</html>

resources/views/layouts/form_ticket.blade.php
<?php
	$nombre = isset($ticket->nombre)? $ticket->nombre : '' ;
	$descripcion = isset($ticket->descripcion)? $ticket->descripcion : '' ;
	$importancia = isset($ticket->importancia)? $ticket->importancia : '' ;
	$create_at = isset($ticket->create_at)? $ticket->create_at : '' ;
?>
@if(isset($edit))
<form class="form-horizontal" method="post" action="{{ route('ticket.update', $ticket->id) }}">
<input name="_method" type="hidden" value="PUT">

	{{ csrf_field() }}
	<div class="form-group">
	    <label for="name" class="col-sm-2 control-label">Nombre</label>
	    <div class="col-sm-3">
			<input id="name" type="text" class="form-control" name="nombre" value="{{$nombre}}" {{ isset($edit) ? 'disabled' : "" }}/>
		</div>
	</div>
	<div class="form-group">
	    <label for="des" class="col-sm-2 control-label">Descripcion</label>
	    <div class="col-sm-3">
			<textarea id="des" class="form-control" name="descripcion">{{$descripcion}}</textarea>
		</div>
	</div>
	<div class="form-group">
	    <label for="imp" class="col-sm-2 control-label">Importancia</label>
	    <div class="col-sm-3">
			<select id="imp" class="form-control" name="importancia">
				<option value="0" {{ ($ticket->importancia==0) ? 'selected="selected"' : "" }}>Urgente</option>
				<option value="1" {{ ($ticket->importancia==1) ? 'selected="selected"' : "" }}>Medio</option>
				<option value="2" {{ ($ticket->importancia==2) ? 'selected="selected"' : "" }}>Bajo</option>
			</select>
		</div>
	</div>
	<div class="form-group">
	    <label for="dat" class="col-sm-2 control-label">Fecha</label>
	    <div class="col-sm-3">
			<input id="dat" class="form-control" type="date" name="create_at" value="{{$create_at}}"  {{ isset($edit) ? 'disabled' : "" }}/> 
		</div>
	</div>
	<input type="submit" class="btn btn-primary" value="modificar" />
	<a href="{{ url('/') }}" class="btn">Atras</a>
</form>
@elseif(isset($create))
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form class="form-horizontal" method="post" action="{{ url('ticket') }}">

	{{ csrf_field() }}
	<div class="form-group">
	    <label for="name" class="col-sm-2 control-label">Nombre</label>
	    <div class="col-sm-3">
			<input id="name" type="text" class="form-control" name="nombre" />
		</div>
	</div>
	<div class="form-group">
	    <label for="des" class="col-sm-2 control-label">Descripcion</label>
	    <div class="col-sm-3">
			<textarea id="des" class="form-control" name="descripcion" ></textarea>
		</div>
	</div>
	<div class="form-group">
	    <label for="imp" class="col-sm-2 control-label">Importancia</label>
	    <div class="col-sm-3">
			<select id="imp" class="form-control" name="importancia" >
				<option value="0">Urgente</option>
				<option value="1">Medio</option>
				<option value="2">Bajo</option>
			</select>
		</div>
	</div>
	<div class="form-group">
	    <label for="dat" class="col-sm-2 control-label">Fecha</label>
	    <div class="col-sm-3">
			<input id="dat" class="form-control" type="date" name="create_at" value="{{Carbon\Carbon::today()->format('Y-m-d')}}" disabled />
		</div>
	</div>
	
	<input type="submit" class="btn btn-primary" value="crear" />
	<a href="{{ url('/') }}" class="btn">Atras</a>
</form>
@endif

resources/views/layouts/table_ticket.blade.php
		<form  class="form-inline" method="POST" action="{{ url('ticket/search') }}">
			{{ csrf_field() }}
			<input type="text" name="search" class="form-control" />
			<input type="submit" value="buscar" class="btn" />
		</form> <br>
		<form method="POST" action="{{ url('ticket/filter') }}">
			{{ csrf_field() }}
			 <div class="col-xs-2">
				<select class="form-control" name="importancia">
					<option value="0" >Urgente</option>
					<option value="1" >Medio</option>
					<option value="2" >Bajo</option>
				</select>
			</div>
			<input type="submit" value="filtrar" class="btn" />
		</form> <br>

<a href="{{ url('ticket/create') }}" class="btn btn-primary">Create</a> <br>
<table class="table table-hover">
	@if(isset($tickets))
		<thead >
			<tr>
				<th>Nombre</th>
				<th>Descripcion</th>
				<th>Importancia</th>
				<th>Fecha</th>
				<th>Acciones</th>
			</tr>
		</thead>
		<tbody>
			@foreach($tickets as $row)
			<tr>
				<td>{{$row->nombre}}</td>
				<td>{{$row->descripcion}}</td>
				<td>
					@if ($row->importancia == 0)
						Urgente
					@elseif ($row->importancia == 1)
					    Medio
					@elseif ($row->importancia == 2)
					    Bajo
					@endif
				</td>
				<td>{{$row->created_at}}</td>
				<td>
					<a href="{{ url('ticket/'.$row->id.'/edit') }}" class="btn btn-warning btn-xs">Modifica</a> 
					<form method="POST" action="{{ route('ticket.destroy', $row->id) }}">
						<input name="_method" type="hidden" value="DELETE">
						{{ csrf_field() }}
						<input type="submit" class="btn btn-danger btn-xs" value="Eliminar" />
					</form>
				</td>
			</tr>
			@endforeach
		</tbody>
	@endif
</table>